name: release

on:
  - workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install --legacy-peer-deps
      - name: Build nx
        run: npx nx run cart:build --configuration=production 

      - name: Get Current version
        id: current_version_cart
        run: |
          ls -lh
          version_act=test_version
          echo "version=$version_act" >> $GITHUB_OUTPUT 

      - name: print version
        run: echo ${{ steps.current_version_cart.outputs.version }} 

      - name: Setup Git
        run: |
          git config user.name "GitHub Bot"
          git config user.email "gituser@example.com"

      - name: Get Current version 2
        id: current_version_cart_2
        run: |
          ls -lh
          echo "test=cat ./dist/apps/cart/package.json | jq -r '.version'" >> $GITHUB_OUTPUT 

      - name: print version 2
        run: echo ${{ steps.current_version_cart_2.outputs.test }} 

      - name: Version
        run: npx nx affected --target version --releaseAs=prerelease --preid=alpha --push=true --baseBranch='master' --syncVersions=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


        

#npx nx run cart:version --releaseAs=prerelease --preid=alpha --push=true