name: release

on:
  - workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Setup Git
        run: |
          git config user.name "GitHub Bot"
          git config user.email "gituser@example.com"
      - run: npm install --legacy-peer-deps
      - name: Version
        run: npx nx affected --target version --releaseAs=prerelease --preid=alpha --push=true --baseBranch='master' --syncVersions=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build nx
        run: npx nx run cart:build --configuration=production 

      - name: Get Current version
        id: current_version_cart
        run: |
          ls -lh
          cat ./dist/apps/cart/package.json | jq -r '.version'
      #echo "version=cat ./dist/apps/cart/package.json | jq -r '.version'" >> $GITHUB_OUTPUT 

      # - name: print version
      #   run: echo ${{ steps.current_version_cart.outputs.version }} 
        

#npx nx run cart:version --releaseAs=prerelease --preid=alpha --push=true