name: release

on:
  - workflow_dispatch

permissions:
  id-token: write
  contents: write
  pull-requests: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ANAS_PAT }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install --legacy-peer-deps
      - name: Build nx
        run: npx nx run cart:build --configuration=production 

      - name: Get Current version
        id: current_version_cart
        run: |
          ls -lh
          version_act=test_version
          echo "version=$version_act" >> $GITHUB_OUTPUT 

      - name: print version
        run: echo ${{ steps.current_version_cart.outputs.version }} 

      - name: Setup Git
        run: |
          git config user.name "GitHub Bot"
          git config user.email "gituser@example.com"

      # - uses: actions/create-github-app-token@v1
      #   id: app-token
      #   with:
      #     # required
      #     app-id: ${{ vars.BOTAPP_ID }}
      #     private-key: ${{ secrets.BOTAPP_PRIVATE_KEY }}

      - name: Version
        run: npx nx affected --base=${{github.ref_name }}~1 --head=${{github.ref_name }} --parallel=1 --target version --releaseAs=prerelease --preid=alpha --push=true --baseBranch='${{github.ref_name }}' --syncVersions=true
        env:
          GITHUB_TOKEN: ${{ secrets.ANAS_PAT }}

#${{ steps.app-token.outputs.token }}

      - name: Get Current version 2
        id: current_version_cart_2
        run: |
          ls -lh
          echo "test=$(cat ./dist/apps/cart/package.json | jq -r '.version')" >> $GITHUB_OUTPUT 

      - name: print version 2
        run: echo ${{ steps.current_version_cart_2.outputs.test }} 

      # - name: Merge branch
      #   run: |
      #     git checkout master
      #     git merge --no-ff ${{ github.ref }}
      #     git push origin master

      - name: create pull request
        run: gh pr create -B master -H ${{github.ref_name }} --title 'Merge ${{ steps.current_version_cart_2.outputs.test }} to master.' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        

#npx nx run cart:version --releaseAs=prerelease --preid=alpha --push=true