name: Tag Push

on:
  push:
    branches:
      - "master"
    tags:
      - "v*.*.*"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Git
        run: |
          echo DO SOMETHING WITH PUSH
          echo deploying tag

      - name: Get Commit SHA
        id: latest_commit_SHA
        run: echo "$(git rev-parse --verify HEAD)"

      - name: Get SHORT Commit SHA
        id: short_sha
        run: echo "$(git rev-parse --short HEAD)"